import Ladrao from '../assets/icones/Ladrao.svg';
import RouboDeCarro from '../assets/icones/RouboDeCarro.svg';
import Briga from '../assets/icones/Briga.svg';
import Arma from '../assets/icones/Arma.svg';

export const IconService = {
  "Assalto": Ladrao,
  "Tentativa de assalto": Ladrao,
  "Roubo de veículo": RouboDeCarro,
  "Furto de peças de veículo": RouboDeCarro,
  "Agressão": Briga,
  "Briga de rua": Briga,
  "Disparo de arma de fogo": Arma,
  "Troca de tiros": Arma, 
  "Sequestro":, 
  "Latrocínio":, 
  "Vandalismo":,
  "Furto de cabos elétricos", 
  "Bloqueio policial", 
  "Perseguição policial", 
  "Helicóptero sobrevoando área policial",
  "Colisão entre carros",
  "Atropelamento de pedestre", 
  "Atropelamento de animal",
  "Capotamento",
  "Caminhão com carga espalhada na pista",
  "Veículo incendiado",
  "Explosão veicular",
  "Veículo abandonado na pista",  
  "Ônibus quebrado bloqueando faixa",
  "Tempestade forte", 
  "Chuva intensa",
  "Vendaval derrubando objetos",
  "Nevoeiro intenso",
  "Fumaça na pista", 
  "Nevasca",
  "Tornado", 
  "Furacão atingindo região",
  "Ciclone com interdição de vias",
  "Tsunami",
  "Terremoto",
  "Tremor de terra com rachaduras",
  "Onda de calor afetando pavimento", 
  "Areia ou poeira reduzindo visibilidade", 
  "Incêndio",
  "Explosão de transformador",
  "Curto-circuito em fiação",
  "Vazamento de gás em rua", 
  "Vazamento químico", 
  "Vazamento de óleo na pista",
  "Vazamento de água com risco de buraco",
  "Fios caídos na via", 
  "Poste caído", 
  "Buraco em via",
  "Afundamento de asfalto", 
  "Erosão em calçada ou pista", 
  "Deslizamento de terra em estrada",
  "Desabamento parcial de muro em calçada", 
  "Desabamento de ponte ou viaduto",
  "Rachadura estrutural em via", 
  "Cratera aberta na pista", 
  "Trecho interditado por obras",
  "Bloqueio parcial por manutenção", 
  "Sinalização danificada", 
  "Semáforo apagado", 
  "Semáforo piscando",
  "Falta de energia afetando cruzamento", 
  "Falha de iluminação pública", 
  "Via sem luz à noite",
  "Lâmpadas queimadas em cruzamento", 
  "Queda de árvore bloqueando pista",
  "Galho grande na pista", 
  "Entulho ou lixo bloqueando faixa", 
  "Materiais de construção na via",
  "Painel publicitário caído", 
  "Telhado ou estrutura metálica na rua", 
  "Vidros espalhados na pista",
  "Animal de grande porte na pista", 
  "Animal silvestre na via",
  "Insetos em enxame na rodovia", 
  "Protesto bloqueando via", 
  "Manifestação com interdição parcial",
  "Tumulto em evento próximo à via", 
  "Rota bloqueada por evento esportivo",
  "Fechamento de rua para show ou feira", 
  "Marcha, carreata ou desfile bloqueando tráfego",
  "Trânsito desviado por evento público", 
  "Fiscalização eletrônica em operação", 
  "Blitz policial",
  "Pedestre desmaiado na calçada",  
  "Afogamento em passagem alagada",
  "Polícia técnica interditando local",
  "Falha em radar ou câmera de trânsito",
  "Pane em semáforo inteligente",
  "Falha de energia em cruzamentos", 
  "Trilhos bloqueando travessia"
};
